app/models/Contato.py
from app import db


class Contato(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    assunto = db.Column(db.String(120), unique=False, nullable=False)
    descricao = db.Column(db.String(120), unique=False, nullable=False)

    def __init__(self, email, assunto, descricao):
        self.email = email
        self.assunto = assunto
        self.descricao = descricao

app/controllers/Contato.py
from app.services.Contato import ContatoService
from app.repositories.Contato import ContatoRepository
from app.utils.Contato import get_body
from flask import jsonify, redirect, url_for, make_response

contato_repository = ContatoRepository()
contato_service = ContatoService(contato_repository)


class ContatoController:
    @staticmethod
    def add(request):
        if request.method == "POST":
            if request.form:
                email = request.form.get("email")
                assunto = request.form.get("assunto")
                descricao = request.form.get("descricao")

                if len(email) >= 5 and len(assunto) >= 5 and len(descricao) >= 5:
                    new_contact = contato_service.add(email, assunto, descricao)

                    return redirect(url_for("contato.contato"))

                return make_response(jsonify(mensagem="Email, Assunto e Descrição são obrigatórios!"))
            
            if request.json:
                email = request.json.get("email")
                assunto = request.json.get("assunto")
                descricao = request.json.get("descricao")

                if not email or not assunto or not descricao:
                    return make_response(jsonify(mensagem="Email, Assunto e Descrição são obrigatórios!"))

                new_contact = contato_service.add(email, assunto, descricao)
                new_contact = get_body(new_contact)

                return make_response(jsonify(mensagem="Contato adicionado com sucesso!", dados=new_contact), 201)

    @staticmethod
    def get_many():
        return contato_service.get_many()

    @staticmethod
    def get_by_id(contact_id):
        contact = contato_service.get_by_id(contact_id)
        if contact is None: return make_response(jsonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

        contact = get_body(contact)

        return make_response(jsonify(contact))

    @staticmethod
    def update_by_id(request, contact_id):
        contact = contato_service.get_by_id(contact_id)
        if contact is None: return make_response(jsonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

        if request.method == "PUT":
            email = request.json.get("email")
            assunto = request.json.get("assunto")
            descricao = request.json.get("descricao")

            contact_to_update = contato_service.update_by_id(contact_id, email, assunto, descricao)
            contact_to_update = get_body(contact_to_update)

            return make_response(
                jsonify(mensagem=f"Contato {contact_id} atualizado com sucesso!", dados=contact_to_update))

        elif request.method == "POST":
            email = request.form.get("email")
            assunto = request.form.get("assunto")
            descricao = request.form.get("descricao")

            contact_to_update = contato_service.update_by_id(contact_id, email, assunto, descricao)
            contact_to_update = get_body(contact_to_update)

            return redirect(url_for("contato.contato"))

    @staticmethod
    def delete_by_id(request, contact_id):
        contact = contato_service.get_by_id(contact_id)
        if contact is None: return make_response(jsonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

        if request.method == "DELETE":
            contact_to_delete = contato_service.delete_by_id(contact_id)
            contact_to_delete = get_body(contact_to_delete)

            return make_response(jsonify(mensagem=f"Contato {contact_id} apagado com sucesso!",
                                             dados=contact_to_delete))

        elif request.method == "GET":
            if contact:
                contato_service.delete_by_id(contact_id)

            return redirect(url_for("contato.contato"))

app/routes/contato.py
from flask import Blueprint, render_template, make_response, jsonify, request, redirect, url_for
from app.components.base_title_text import base_title_text
from app.components.base_input_text import base_input_text
from app.constants.contato import CONTACT_TEXT, EMAIL_INPUT, ASSUNTO_INPUT, DESCRICAO_INPUT
from app.models.Contato import Contato
from app.controllers.Contato import ContatoController

contato_blueprint = Blueprint('contato', __name__)


@contato_blueprint.route('/contato')
def contato():
    all_contacts = get_many().json
    return render_template("contato.html", contact=base_title_text(CONTACT_TEXT),
                           input_email=base_input_text(EMAIL_INPUT), input_assunto=base_input_text(ASSUNTO_INPUT),
                           input_descricao=base_input_text(DESCRICAO_INPUT, "textarea"), contacts=all_contacts)


@contato_blueprint.route('/contato/add', methods=["GET", "POST"])
def add():
    if request.method == "POST":
        email = request.form.get("email")
        assunto = request.form.get("assunto")
        descricao = request.form.get("descricao")

        novo_contato = ContatoController.add(email, assunto, descricao)

    return redirect(url_for("contato.contato"))


@contato_blueprint.route('/contato/api/', methods=["GET"])
def get_many():
    contatos = Contato.get_all()

    return make_response(jsonify(contatos))


@contato_blueprint.route('/contato/<int:contact_id>/', methods=["GET"])
def get_by_id(contact_id: int):
    contact = Contato.query.filter_by(id=contact_id).first()
    if request.method == "GET":
        if contact:
            print(contact)

            return make_response(jsonify(mensagem=f"Contato {contact_id} atualizado com sucesso!", dados=contact))

        return make_response(jonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

    return contato()


@contato_blueprint.route('/contato/<int:contact_id>/update', methods=["GET", "PUT"])
def update_by_id(contact_id: int):
    contact = Contato.query.filter_by(id=contact_id).first()
    if request.method == "PUT":
        if contact:
            contact.update(request.json)

            return make_response(jsonify(mensagem=f"Contato {contact_id} atualizado com sucesso!", dados=request.json))

        return make_response(jsonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

    return contato()


@contato_blueprint.route('/contato/<int:contact_id>/delete', methods=["GET", "DELETE"])
def delete_by_id(contact_id: int):
    contact = Contato.query.filter_by(id=contact_id).first()
    if request.method == "DELETE":
        if contact:
            contact.apagar()

            return make_response(jsonify(mensagem=f"Contato {contact_id} apagado com sucesso!"))

        return make_response(jsonify(mensagem=f"Contato com id {contact_id} não encontrado!"))

    elif request.method == "GET":
        if contact:
            contact.apagar()

        return redirect(url_for("contato.contato"))

app/views/contato.py
from flask import Blueprint, render_template, make_response, jsonify, request
from app.components.base_title_text import base_title_text
from app.constants.contato import CONTACT_TEXT, EMAIL_INPUT, ASSUNTO_INPUT, DESCRICAO_INPUT
from app.controllers.Contato import ContatoController

contato_blueprint = Blueprint('contato', __name__)


@contato_blueprint.route('/contato')
def contato():
    all_contacts = get_many().json
    return render_template("contato.html", contact=base_title_text(CONTACT_TEXT), contacts=all_contacts)


@contato_blueprint.route('/contato/add', methods=["GET", "POST"])
def add():
    return ContatoController.add(request)


@contato_blueprint.route('/contato/api/', methods=["GET"])
def get_many():
    return make_response(jsonify(ContatoController.get_many()))


@contato_blueprint.route('/contato/<int:contact_id>/', methods=["GET"])
def get_by_id(contact_id: int):
    return ContatoController.get_by_id(contact_id)


@contato_blueprint.route('/contato/<int:contact_id>/update', methods=["POST", "PUT"])
def update_by_id(contact_id: int):
    return ContatoController.update_by_id(request, contact_id)


@contato_blueprint.route('/contato/<int:contact_id>/delete', methods=["GET", "DELETE"])
def delete_by_id(contact_id: int):
    return ContatoController.delete_by_id(request, contact_id)

app/views/home.py
from flask import Blueprint, render_template, redirect, url_for
from app.components.base_title_text import base_title_text
from app.constants.home import ABOUT_TEXT, REASONS_TO_STUDY

home_blueprint = Blueprint('home', __name__)


@home_blueprint.route('/home')
def home():
    return render_template('home.html', about_university=base_title_text(ABOUT_TEXT), reasons=REASONS_TO_STUDY)


@home_blueprint.route('/')
def index():
    return redirect(url_for('home.home'))

app/views/quem_somos.py
from flask import Blueprint, render_template
from app.components.base_title_text import base_title_text
from app.constants.quem_somos import ABOUT_US_TEXT, OBJECTIVES_TEXT

quem_somos_blueprint = Blueprint('quemsomos', __name__)


@quem_somos_blueprint.route('/quemsomos')
def quemsomos():
    return render_template("quem_somos.html", about_us=base_title_text(ABOUT_US_TEXT),
                           objectives=base_title_text(OBJECTIVES_TEXT))

app/templates/404_not_found.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UNES - Página não encontrada! </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/404_not_found.css') }}">
</head>
<body>
    <main>
        <div class="background_azul">
            <div class="not_found_message">
                <div class="not_found_message__title">
                    <h1>404: Página não encontrada!</h1>
                </div>
                <div class="not_found_message__text">
                    <p>Parece que você está esperando por uma página que não existe...</p>
                </div>
            </div>

            <div class="return_homepage">
                <button class="return_homepage__button">
                    <a type="button" class="banner__btn" href="{{ url_for('contato.contato') }}">
                        <p class="banner__btn_title p-3">Voltar para home</p>
                    </a>
                </button>
            </div>
        </div>
        
    </main>
    
</body>
</html>

app/templates/contato.html
{% extends 'base.html' %}

{% block title %}Contato{% endblock %}

{% block body %}
<main class="apresentacao">

    <section class="apresentacao__conteudo">
        <div class="apresentacao__conteudo__texto">
            {{ contact | safe }}
        </div>

        <div class="apresentacao__conteudo__divider"></div>
    </section>
    {% if contacts %}
    <section class="apresentacao__contatos">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Email</th>
                    <th scope="col">Assunto</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
    
             <tbody>
                {% for contact in contacts %}
                   <tr>
                      <td>{{ contact.id }}</td>
                      <td>{{ contact.email }}</td>
                      <td>{{ contact.assunto }}</td>
                      <td>{{ contact.descricao }}</td>
                      <td>
                        <!-- Botão Editar -->
                        <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#ModalEditar{{ contact.id }}" data-bs-whatever="@editar">
                            <i class="mdi mdi-pencil"></i>
                        </button>
    
                        <!-- Modal Editar -->
                        <div class="modal fade" id="ModalEditar{{ contact.id }}" tabindex="-1" aria-labelledby="ModalLabelEditar{{ contact.id }}" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="ModalLabelEditar{{ contact.id }}">Tem certeza que deseja editar esse contato?</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
    
                                    <div class="modal-body">
                                        <form action="{{ url_for('contato.update_by_id', contact_id=contact.id) }}" method="POST">
    
                                            <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1">ID</span>
                                                <input type="text" name="id" id="id" class="form-control" placeholder="id" aria-label="id" value="{{ contact.id }}" aria-describedby="basic-addon1" disabled>
                                            </div>
    
                                            <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1">@</span>
                                                <input type="email" name="email" id="assunto" class="form-control" placeholder="email" aria-label="email" value="{{ contact.email }}" aria-describedby="basic-addon1">
                                            </div>
    
                                            <div class="mb-3">
                                                <label for="assunto" class="col-form-label">Assunto:</label>
                                                <textarea class="form-control" name="assunto" id="asssunto">{{ contact.assunto }}</textarea>
                                            </div>
    
                                            <div class="mb-3">
                                                <label for="descricao" class="col-form-label">Descrição:</label>
                                                <textarea class="form-control" name="descricao" id="descricao">{{ contact.descricao }}</textarea>
                                            </div>
    
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                                                <button type="submit" class="btn btn-primary">Editar</button>
                                            </div>
    
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
    
                        <!-- Botão Apagar -->
                        <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#ModalApagar{{ contact.id }}" data-bs-whatever="@apagar">
                            <i class="mdi mdi-trash-can-outline"></i>
                        </button>
    
                        <!-- Modal Apagar -->
                        <div class="modal fade" id="ModalApagar{{ contact.id }}" tabindex="-1" aria-labelledby="ModalLabelApagar{{ contact.id }}" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="ModalLabelApagar{{ contact.id }}">Tem certeza que deseja apagar esse contato?</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1">ID</span>
                                            <input type="text" class="form-control" placeholder="id" aria-label="id" value="{{ contact.id }}" aria-describedby="basic-addon1" disabled>
                                        </div>
                                        <div class="input-group mb-3">
                                            <span class="input-group-text" id="basic-addon1">@</span>
                                            <input type="text" class="form-control" placeholder="email" aria-label="email" value="{{ contact.email }}" aria-describedby="basic-addon1" disabled>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>       
                                        <a class="btn btn-danger" role="button" href="{{ url_for('contato.delete_by_id', contact_id=contact.id) }}">Apagar</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                      </td>
                   </tr>
                {% endfor %}
             </tbody>
            </table>   
        </div>
        
    </section>
    {% endif %}
</main>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}Sobre a universidade{% endblock %}

{% block body %}
<main class="apresentacao">
    <section class="apresentacao__conteudo">
        <div class="apresentacao__conteudo__texto">
            <div>
                <h2 class="apresentacao__conteudo__texto_title text-center fw-normal">Sua jornada acadêmica com total visibilidade e praticidade</h2>
                <p class="apresentacao__conteudo__texto_subtitle text-center mt-3 mb-5">Oferecemos uma educação otimizada para o seu sucesso. Junte-se a nós e assuma o comando do seu futuro.</p>
            </div>
        </div>
    </section>

    <section class="cards_vantagens d-flex justify-content-center">
        <div class="cards_vantagens__card card mb-3 rounded-4 shadow">
            <div class="row g-5">
                <div class="col-md-8">
                    <div class="card-body justify-content-between align-bottom">
                        <h5 class="card-title fw-normal">Educação de alta qualidade, com amplas oportunidades para crescimento pessoal e profissional.</h5>
                        <p class="card-text"><strong>Lorem ipsum</strong> dolor sit amet consectetur adipisicing elit. Deserunt vero laboriosam error illo ea. A dolores voluptas reiciendis facilis tempore. </p>
                        <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur eaque et molestias voluptate fuga at molestiae voluptatibus.</p>
                        <div class="d-flex pt-5">
                            <a type="button" class="banner__btn" href="{{ url_for('contato.contato') }}" data-bs-toggle="modal" data-bs-target="#modalFaleConosco">
                <p class="banner__btn_title">Entre em contato</p>
            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="static/imagens/pingu.gif" class="img-fluid rounded-end-3" alt="...">
                </div>
            </div>
        </div>
    </section>

    <section class="row nossos_numeros my-5">
        <h2 class="apresentacao__conteudo__texto_title text-center fw-normal">Nossos números</h2>
        <div class="col-lg-3 col-sm-12 my-4">
            <div class="d-flex row text-center">
                <h2 class="fw-bold">+100mil</h2>
                <h6 class="fw-medium">Estudantes</h6>
            </div>
        </div>
        <div class="col-lg-3 col-sm-12 my-4">
            <div class="d-flex row text-center">
                <h2 class="fw-bold">+75mil</h2>
                <h6 class="fw-medium text-wrap">Certificados entregues</h6>
            </div>
        </div>
        <div class="col-lg-3 col-sm-12 my-4">
            <div class="d-flex row text-center">
                <h2 class="fw-bold">+75%</h2>
                <h6 class="fw-medium">Aprovação</h6>
            </div>
        </div>
        <div class="col-lg-3 col-sm-12 my-4">
            <div class="d-flex row text-center">
                <h2 class="fw-bold">100</h2>
                <h6 class="fw-medium">Unidades</h6>
            </div>
        </div>
    </section>

    <section class="apresentacao__conteudo my-5">
        <div class="apresentacao__conteudo_motivos container text-center">
            <div class="apresentacao__conteudo_motivos_cards row justify-content-evenly px-4 py-5 rounded-4 shadow-sm gap-3">
                <h2 class="apresentacao__conteudo__texto_title p-0 pb-5 fw-normal">Motivos para estudar</h2>
                {% for reason in reasons %}
                <div class="card card_reasons border-0 rounded-2 bg-white shadow col-sm-12 col-lg-2 p-0">
                    <img src="/static/imagens/pingu.gif" alt="" class="border-0 rounded-top-3">
                    <div class="card-body p-3">
                        <h5 class="card-title p-2 fw-normal">{{ reason.get('title')}}</h5>
                        <p class="card-text text-start fs-6 fw-lighter lh-1">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati laboriosam aperiam harum mollitia, maxime.</p>
                        
                        <div class="d-flex justify-content-start pt-4 pb-1">
                        <a href="#" class="nav-link p-1 border-0 fw-light">Saiba mais <i class="mdi mdi-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

app/templates/quem_somos.html
{% extends 'base.html' %}

{% block title %}Quem somos{% endblock %}

{% block body %}
<section class="apresentacao__conteudo">
    <div class="apresentacao__conteudo__texto">
        <div class="d-flex row">
            <h2 class="apresentacao__conteudo__texto_title text-black text-center fw-normal">Somos <span class="apresentacao__conteudo__texto_title_underline text-decoration-underline">apaixonados</span> pela educação: comprometidos com o conhecimento e o progresso!</h2>
            <a type="button" class="banner__btn_white" href="{{ url_for('contato.contato') }}">
                <p class="p-2 m-0">
                    Saiba mais
                    <i class="mdi mdi-arrow-down"></i>
                </p>
            </a>
        </div>
    </div>
</section>

<section class="cards_vantagens d-flex row justify-content-center">
    <div class="cards_vantagens__card card mb-3 rounded-4 shadow">
        <div class="row g-5">
            <div class="col-md-8">
                <div class="card-body justify-content-between align-bottom">
                    <h5 class="card-title fw-normal">Quem somos</h5>
                    <p class="card-text"><strong>Lorem ipsum</strong> dolor sit amet consectetur adipisicing elit. Deserunt vero laboriosam error illo ea. A dolores voluptas reiciendis facilis tempore. </p>
                    <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur eaque et molestias voluptate fuga at molestiae voluptatibus.</p>
                    <div class="d-flex pt-5">
                        <a type="button" class="banner__btn" href="{{ url_for('contato.contato') }}" data-bs-toggle="modal" data-bs-target="#modalFaleConosco">
                            <p class="banner__btn_title">Entre em contato</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <img src="static/imagens/pingu.gif" class="img-fluid rounded-end-3" alt="...">
            </div>
        </div>
    </div>

    <div class="apresentacao__conteudo__texto">
        {{ objectives | safe }}
    </div>
</section>
{% endblock %}